name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dugiahuy/fista.dev:$(date +%s)
    - name: Login to Docker Hub
      run: printf $DOCKER_PASS | base64 -d  | docker login -u dugiahuy --password-stdin
    - name: Push image to Docker Hub
      run: docker push dugiahuy/fista.dev:$(date +%s)
